apiVersion: v1
kind: Service

# resource name
metadata:
  name: comingsoon-page-service
  namespace: comingsoon


# defines configuration of the service
spec:
  # find the pods that should be exposed by this service.
  #  service will route traffic to any pod that matches this label
  selector:
    app: comingsoon-page
  
# ClusterIP (default), LoadBalancer (works on cloud), NodePort (most used)
  type: NodePort
  
  ports:
  - protocol: TCP
    port: 80 
    # containerPort
    targetPort: 80 